### PR TITLE
Fix ASI with multiline comments

### LINKED ISSUE #1803: ASI: insert semicolon when multiline comment occurs, too.
These bug titles are wordy and hard to file =)

There's an ASI bug in v8, spidermonkey, and TypeScript which I noticed today, but apparently Traceur does okay with it --- with the exception that it doesn't deal with the line-feed before `=>` if it occurs in a multi-line comment.

This is inconsistent with the way ASI rules work in browsers, so it's probably not what you want

### PR DESCRIPTION
**Pull request by arv**
A multiline comment is treated as a new line for ASI when it
contains a new line.

Fixes #1803, #1809

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton PTAL

I guess this is actually a regression (a fews years old though). We used to compare the line numbers of the tokens. I refactored that because it was too slow and therefore we got this error.

**Comment by caitp** [comment]
scanning the source for newlines in comments seems expensive --- doesn't the scanner already go through the comment anyways? It seems useful to reuse the work that was already done

This might be related, but I found I was able to make the repl hang pretty badly and crash the browser when inserting a `/*` in a (pretty small, 3 line) program --- I was never able to insert the `*/` because of the crash. Maybe comment scanning is done in a bit of a bad fashion right now?

**Comment by caitp** [comment]
If you want a repro of the crash, try [this](https://google.github.io/traceur-compiler/demo/repl.html#var%20fn%20%3D%20(a)%20%2F*%0A%20%20%3D%3E%20a%0A%20%0Afn(1)%3B)

**Comment by caitp** [comment]
I'm going to open a second issue about that just to get some GH activity for today =)

**Comment by arv** [comment]
> I'm going to open a second issue about that just to get some GH activity for today =)

:-)

The thing is that we do not keep track of comments. We have a skipMultiLineComment function but it moves the scanner forward.

https://github.com/google/traceur-compiler/blob/master/src/syntax/Scanner.js#L606-L615

**Comment by caitp** [comment]
Right, but wouldn't it make sense to track (either in the scanner, or in the token itself), whether skipping whitespace or comments found a newline or not? That way you could avoid re-scanning stuff you've already seen

**Comment by arv** [comment]
The price for this is only for `[no LineTerminator here]` and it only needs to scan the characters between the last token and next token. Having large comments in that position seems too rare to add this kind of tracking globally.

**Comment by caitp** [comment]
fair enough :>

File: src/syntax/Scanner.js [hunk 1]
```diff
@@ -527,17 +527,31 @@ function peekTokenNoLineTerminator() {
...
+    // new line.
     if (code === 47) {  // '/'
       code = input.charCodeAt(++i);
       // End of line comments always mean a new line is present.
-      if (code === 47)  // '/'
+      if (code === 47) {  // '/'
         return null;
-      i = input.indexOf('*/', i) + 2;
+      }
+
```
Comment (johnjbarton) [inline src/syntax/Scanner.js]: I don't understand why we don't need to check that `code === 42` at this point.  It seems like `/! */` would also work here.

Comment (arv) [inline src/syntax/Scanner.js]: I thought the same thing at first. The reason why we don't need to check this is that we are only checking the text between the last token and the next token. That means that the text is either whitespace, a comment or a sequence of these.

I'll add a comment.

Comment (arv) [inline src/syntax/Scanner.js]: That makes me realize that this can be simplified further. All we need to look for is a newline since either:

 - There is a line break in whitespace
 - There is a `//` comment, in which case we have a new line at the end of the comment.
 - If a multiline comment and it contains a new line treat the comment as a newline.

**Comment by arv** [comment]
@johnjbarton Do you have any other comments?

**Comment by johnjbarton** [comment]
Sorry I'm confused. You said you only need to look for a new line but the code hasn't changed as far as  I can tell.

**Comment by arv** [comment]
Yeah, something failed in that last git push. The correct code is now in this PR.

**Comment by johnjbarton** [comment]
Well that's a win, LGTM
