### PR TITLE
Fix template object caching

### LINKED ISSUE #1845: Template literal caching is not spec compliant
Traceur uses the "location" as the "key" for the caching of the template literal object (the frozen array) but the spec changed to use the string values as the key.

### PR DESCRIPTION
**Pull request by arv**
This updates the template object caching to match the spec.

2 identical templates should use the same template object. Previously
only the location was used to determine the hashing.

Fixes #1845

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton PTAL

The PlaceholderParser changes are ported over from the strong mode branch, 0b84ba066bea901b24cd891538a004cb0229c081

File: src/codegeneration/PlaceholderParser.js [hunk 1]
```diff
@@ -20,7 +20,6 @@ import {
 } from '../syntax/trees/ParseTreeType.js';
 import {IdentifierToken} from '../syntax/IdentifierToken.js';
 import {LiteralToken} from '../syntax/LiteralToken.js';
-import {Map} from '../runtime/polyfills/Map.js';
```
Comment (johnjbarton) [inline src/codegeneration/PlaceholderParser.js]: Does this create a possibly implicit dependence on browser, browser version or V8 version?

Comment (arv) [inline src/codegeneration/PlaceholderParser.js]: I was torn about this one. We already depend on a global Map in other places.

The difference due to this change is that we get the builtin if provided; if not we get it implicitly through the polyfill.

File: src/codegeneration/TemplateLiteralTransformer.js [hunk 2]
```diff
@@ -38,74 +37,79 @@ import {
...
-  return parseExpression `Object.freeze(Object.defineProperties(${cooked}, {
-    raw: {
-      value: Object.freeze(${raw})
+function createGetTemplateObject(elements) {
+  // In case cooked and raw have the same value (which is quite common) we
+  // do not need to repeat the array literal.
+  //
+  // $traceurRuntime.getTemplateObject(['a', 'b'])
+  // $traceurRuntime.getTemplateObject(['\\n'], ['\n'])
+
```
Comment (johnjbarton) [inline src/codegeneration/TemplateLiteralTransformer.js]: I don't understand the example.   I think there are accidentally too many 2-s here: cooked+raw, `i += 2`, `['a', 'b'].length === 2`, two arguments to the second example.  It's hard to tell what is meant by "cooked and raw have the same value".

Comment (caitp) [inline src/codegeneration/TemplateLiteralTransformer.js]: first example has a single array literal, because the cooked values and raw values are identical. The second example has 2 array literals, because the cooked string is different from the raw string

(at least, I think that's what this is getting at).

Comment (caitp) [inline src/codegeneration/TemplateLiteralTransformer.js]: 2 array literals/arguments -> cooked strings and raw strings are different.
1 array literal/argument -> cooked strings and raw strings have identical values (common case, no escape sequences are used)

Comment (johnjbarton) [inline src/codegeneration/TemplateLiteralTransformer.js]: Perhaps you can move the second example in to the description, since I gather it is an example where cooked must be supplied rather than a second example of cooked and raw the same.

File: src/codegeneration/PlaceholderParser.js (hunk 1 above)
Comment (johnjbarton) [inline src/codegeneration/PlaceholderParser.js]: Oh, the global set by the polyfill.  Ok, no import is fine.

**Comment by johnjbarton** [comment]
LGTM

File: src/codegeneration/TemplateLiteralTransformer.js (hunk 2 above)
Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: I cleaned up the comment and moved it to the jsdoc.
