### PR TITLE
Fix Map/Set polyfill detection

### LINKED ISSUE #1650: Map on Safari throws error when constructor is passed arguments
After compiling the following with Traceur (using es6ify):

```
var some var = new Map([
      ['key', 'data']
])
```

Safari throws

```
[Error] TypeError: Map constructor does not accept arguments
```

I see from http://kangax.github.io/compat-table/es6/ that Safari does not support this feature of ES6. Are there any plans to polyfill it in Safari?

Traceur version: 0.0.79
Safari version: 8.0.2

### PR DESCRIPTION
**Pull request by arv**
Safari does not support ES6 Map/Set correctly which leads to trouble.
Be more strict in detecting whether the native Map/Set is good enough.

Fixes #1650, #1810

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton PTAL

File: src/runtime/polyfills/Map.js [hunk 1]
```diff
@@ -192,19 +192,21 @@ Object.defineProperty(Map.prototype, Symbol.iterator, {
...
-    global.Map = Map;
+function needsPolyfill(global) {
+  var {Map, Symbol} = global;
+  if (!Map || !$traceurRuntime.hasNativeSymbol() ||
+      !Map.prototype[Symbol.iterator] || !Map.prototype.entries) {
+    return true;
+  }
+  try {
+    return new Map([[]]).size !== 1;
+  } catch (e) {}
```
Comment (johnjbarton) [inline src/runtime/polyfills/Map.js]: I think this would be clearer with the `return` in the `catch` clause .

File: src/runtime/runtime.js [hunk 2]
```diff
@@ -459,10 +459,15 @@
       return argument;
     }
 
+    var hasNativeSymbol = false;
```
Comment (johnjbarton) [inline src/runtime/runtime.js]: I would leave this `undefined` to reinforce that we will set it in one of the `if` branches that will execute before we exit.

**Comment by johnjbarton** [comment]
LGTM
