### PR TITLE
Parenthesize complex operands in NewExpression

### LINKED ISSUE #1811: templates: more or less the same as chromium:450942
The following code (from https://crrev.com/996223003/):

```js
(function testCallNew2() {
  "use strict";
  var log = [];
  function tag(x) {
    log.push(x);
    if (!(this instanceof tag)) {
      return tag;
    }
    this.x = x === void 0 ? null : x;
    return this;
  }
  var instance = new tag`x``y``z`;
  console.log("instance instanceof tag: " + instance instanceof tag);
  console.log("tag.prototype === instance.__proto__: " +
              (tag.prototype === Object.getPrototypeOf(instance)) );
  console.log(JSON.stringify(log));
})();
```

results in `new tag($__0)($__1)($__2);`, as opposed to `new(tag($__0)($__1)($__2));` (which would match the behaviour of Firefox and the above referenced patch). Similarly, also fails the original repro case for [the bug](https://crbug.com/450942).

Someone who is better at reading the spec BNF than me should be able to clarify the appropriate behaviour, but for now I'm leaning towards matching what Firefox is doing.

### PR DESCRIPTION
**Pull request by caitp**
Closes #1811

### CODE REVIEW

**Comment by caitp** [comment]
This one seems to work better :<

File: src/outputgeneration/ParseTreeWriter.js [hunk 1]
```diff
@@ -1006,9 +1006,12 @@ export class ParseTreeWriter extends ParseTreeVisitor {
    * @param {NewExpression} tree
    */
   visitNewExpression(tree) {
+    var complexOperand = tree.operand.operand !== void 0;
```
Comment (arv) [inline src/outputgeneration/ParseTreeWriter.js]: The writer should not have logic on it.

We never use undefined for valid properties. The right approach is to check the type.

So, if I parse

```js
new a.b.c()
```

Then the operand is `a.b.c` and you now want to add parens around that? That does not seem correct.

I think we need to look at the AST we generate. Is it correct? I think it is. However, our transformer is not aware of `new`.

```js
new a `b` `c`
```

is transformed into

```js
new a($__0)($__1)
```

when we need to transform it into

```js
new (a($__0)($__1))
```

File: test/feature/TemplateLiterals/NewExpression.js [hunk 2]
```diff
@@ -0,0 +1,44 @@
+// Options: --block-binding
+
+{
+  let i = 0, log = [];
+  this.logger = function(...e) {
+    log.push(e.join(" "));
```
Comment (arv) [inline test/feature/TemplateLiterals/NewExpression.js]: Traceur uses Google's JS style guide which means that we prefer single quotes.

File: src/outputgeneration/ParseTreeWriter.js (hunk 1 above)
Comment (caitp) [inline src/outputgeneration/ParseTreeWriter.js]: Right now, it's relying on the vm's own idea of precedence, but I think the parser is mostly getting it right, so always parenthesizing the operand should be fine (just produces some ugly code).

Maybe it makes more sense to cover "complex" operands in transformNewExpression()

Comment (arv) [inline src/outputgeneration/ParseTreeWriter.js]: The writer is supposed to just write the tree. It is supposed to round trip.

Comment (caitp) [inline src/outputgeneration/ParseTreeWriter.js]: I get that, I'm just trying to figure out how to do this in ParseTreeTransformer =)

Comment (arv) [inline src/outputgeneration/ParseTreeWriter.js]: We need to add a transformNewExpression to TemplateLiteralTransformer. Not yet sure how to best detect that the operand contains a template literal.

File: src/codegeneration/TemplateLiteralTransformer.js [hunk 3]
```diff
@@ -198,6 +199,21 @@ export class TemplateLiteralTransformer extends TempVarTransformer {
...
+    if (tree.operand) {
+      var operand = tree.operand;
+      do {
+        // If operand contains a tagged TemplateLiteral, parenthesize the entire
+        // operand.
+        if (operand.operand && operand.type === TEMPLATE_LITERAL_EXPRESSION) {
+          tree.operand = new ParenExpression(null, tree.operand);
+          break;
+        }
+      } while (operand = operand.operand);
```
Comment (caitp) [inline src/codegeneration/TemplateLiteralTransformer.js]: New approach, hows that?

File: src/codegeneration/TemplateLiteralTransformer.js [hunk 4]
```diff
@@ -198,6 +199,21 @@ export class TemplateLiteralTransformer extends TempVarTransformer {
...
+    }
+    return ParseTreeTransformer.prototype.transformNewExpression.call(this, tree);
```
Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: Use `super.transformNewExpression` (I see that there is some old code above that uses ES5 style super)

File: src/codegeneration/TemplateLiteralTransformer.js [hunk 5]
```diff
@@ -16,7 +16,8 @@ import {
   BINARY_EXPRESSION,
   COMMA_EXPRESSION,
   CONDITIONAL_EXPRESSION,
-  TEMPLATE_LITERAL_PORTION
+  TEMPLATE_LITERAL_PORTION,
```
Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: not used

File: src/codegeneration/TemplateLiteralTransformer.js [hunk 6]
```diff
@@ -198,6 +199,21 @@ export class TemplateLiteralTransformer extends TempVarTransformer {
     return ParseTreeTransformer.prototype.transformFunctionBody.call(this, tree);
   }
 
+  transformNewExpression(tree) {
+    if (tree.operand) {
+      var operand = tree.operand;
```
Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: use `let`

File: src/codegeneration/TemplateLiteralTransformer.js [hunk 7]
```diff
@@ -198,6 +199,21 @@ export class TemplateLiteralTransformer extends TempVarTransformer {
...
+      do {
+        // If operand contains a tagged TemplateLiteral, parenthesize the entire
+        // operand.
+        if (operand.operand && operand.type === TEMPLATE_LITERAL_EXPRESSION) {
```
Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: needs a type check, accessing non existing properties is something we try to not do.

File: src/codegeneration/TemplateLiteralTransformer.js [hunk 8]
```diff
@@ -198,6 +199,21 @@ export class TemplateLiteralTransformer extends TempVarTransformer {
...
+          tree.operand = new ParenExpression(null, tree.operand);
```
Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: trees are immutable (but we do not actually freeze the for performance reasons)

File: src/codegeneration/TemplateLiteralTransformer.js (hunk 3 above)
Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: This approach is solid.

File: src/codegeneration/TemplateLiteralTransformer.js (hunk 7 above)
Comment (caitp) [inline src/codegeneration/TemplateLiteralTransformer.js]: I'm not sure how to best do that, since `operand = operand.operand` is going to happen when continuing the loop

Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: Actually, just change it to:

```js
if (operand.type === TEMPLATE_LITERAL_EXPRESSION && operand.operand !== null) {
...
```

File: src/codegeneration/TemplateLiteralTransformer.js (hunk 5 above)
Comment (caitp) [inline src/codegeneration/TemplateLiteralTransformer.js]: it looks like it's used in this file to me

Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: Sorry, my bad... I got tricked by the diff.

File: src/codegeneration/TemplateLiteralTransformer.js [hunk 9]
```diff
@@ -198,6 +200,21 @@ export class TemplateLiteralTransformer extends TempVarTransformer {
...
   }
 
+  transformNewExpression(tree) {
+    if (tree.operand) {
+      let operand = tree.operand;
+      do {
+        // If operand contains a tagged TemplateLiteral, parenthesize the entire
+        // operand.
+        if (operand.type === TEMPLATE_LITERAL_EXPRESSION && operand.operand !== null) {
+          tree = createNewExpression(createParenExpression(tree.operand), tree.args);
```
Comment (arv) [inline src/codegeneration/TemplateLiteralTransformer.js]: This works but in general it is better to use the constructors so that the location is not lost.

```js
tree = new NewExpression(tree.location,
    createParenExpression(tree.operand), tree.args);
```

since the paren expression is generated code there is no location for it so either `createParenExpression(expr)` or `new ParenExpression(null, expr)` is fine.

File: src/codegeneration/TemplateLiteralTransformer.js [hunk 10]
```diff
@@ -198,6 +200,21 @@ export class TemplateLiteralTransformer extends TempVarTransformer {
...
   }
 
+  transformNewExpression(tree) {
+    if (tree.operand) {
+      let operand = tree.operand;
+      do {
+        // If operand contains a tagged TemplateLiteral, parenthesize the entire
+        // operand.
+        if (operand.type === TEMPLATE_LITERAL_EXPRESSION && operand.operand !== null) {
+          tree = new NewExpression(tree.location, createParenExpression(tree.operand), tree.args);
```
Comment (caitp) [inline src/codegeneration/TemplateLiteralTransformer.js]: done

**Comment by arv** [comment]
LGTM

Can you add yourself to AUTHORS too?

**Comment by caitp** [comment]
yeah, done

**Comment by arv** [comment]
great... landing
