### PR TITLE
ExplodeExpressionTransformer should not transform function bodies

### LINKED ISSUE #1934: Wrong assignment in await statements
The following code doesn't work (cf [repl](http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--annotations%20--array-comprehension%20--async-functions%20--async-generators%20--exponentiation%20--export-from-extended%20--for-on%20--generator-comprehension%20--member-variables%20--proper-tail-calls%20--require%20--source-maps%20--symbols%20--types%20%0A%0Aasync%20function%20test()%20%7B%0A%20%20return%20await%20new%20Promise(%20(%20resolve%2C%20reject%20)%20%3D%3E%20%7B%0A%0A%20%20%20%20%20%20let%20escapedQuery%20%3D%20%22test%22.replace(%20%2F%5B%5C%5C%26%7C!()%7B%7D%5B%5C%5D%5E%22~*%3F%3A%2B-%5D%2Fg%2C%20'%5C%5C%241'%20)%3B%0A%20%20%20%20%20%20alert(%20escapedQuery%20)%3B%0A%0A%20%20%7D%20)%3B%0A%7D%0A%0Atest()%0A)). It alerts the function replace instead of the result of the function call.

```js
async function test() {
  return await new Promise( ( resolve, reject ) => {

      let escapedQuery = "test".replace( /[\\&|!(){}[\]^"~*?:+-]/g, '\\$1' );
      alert( escapedQuery );

  } );
}

test()
```

### PR DESCRIPTION
**Pull request by arv**
Fixes #1934

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton PTAL

File: src/codegeneration/ExplodeExpressionTransformer.js [hunk 1]
```diff
@@ -750,6 +752,43 @@ export class ExplodeExpressionTransformer extends ParseTreeTransformer {
...
+    // =>
+    // $0 = function () {}, $0
+    return this.createCommaExpressionBuilder_().build(tree);
+  }
+
+  transformArrowFunctionExpression(tree) {
+    // () => {}
+    // =>
+    // $0 = () => {}, $0
+    return this.createCommaExpressionBuilder_().build(tree);
```
Comment (johnjbarton) [inline src/codegeneration/ExplodeExpressionTransformer.js]: Here it looks like `ExplodeExpressionTransformer` does not descend into the arrow function body and I don't see a change involving function call so I don't understand how this can fix #1934.

File: test/unit/codegeneration/ExplodeExpressionTransformer.js [hunk 2]
```diff
@@ -232,4 +232,14 @@ suite('ExplodeExpressionTransformer.js', function() {
...
+  testExplode('FunctionExpression', 'a.b = function() { c.d }',
+      '$0 = function() {\n  c.d;\n}, a.b = $0, $0');
+  testExplode('Arrow', 'a.b = () => { c.d }',
+      '$0 = () => {\n  c.d;\n}, a.b = $0, $0');
+  testExplode('Arrow', 'a.b = () => c.d', '$0 = () => c.d, a.b = $0, $0');
+  testExplode('ClassExpression', 'a.b = class { m() { c.d } }',
+      '$0 = class {\n  m() {\n    c.d;\n  }\n}, a.b = $0, $0');
+  testExplode('ClassExpression', 'a.b = class extends c.d { m() { e.f } }',
+      '$0 = c.d, $1 = class extends $0 {\n  m() {\n    e.f;\n  }\n}, ' +
+      'a.b = $1, $1');
```
Comment (johnjbarton) [inline test/unit/codegeneration/ExplodeExpressionTransformer.js]: None of the tests seem to relate directly to #1934, so I'm confused...

File: src/codegeneration/ExplodeExpressionTransformer.js (hunk 1 above)
Comment (arv) [inline src/codegeneration/ExplodeExpressionTransformer.js]: We do not want to descend into the arrow function. There is a test for this. My conclusing in that bug was wrong.

File: test/unit/codegeneration/ExplodeExpressionTransformer.js (hunk 2 above)
Comment (arv) [inline test/unit/codegeneration/ExplodeExpressionTransformer.js]: The point is that we should not recurse into functions. The ExplodeExpressionTransformer should only operate on expressions.

**Comment by johnjbarton** [comment]
Ok thanks, makes sense.

LGTM
