### PR TITLE
Fix issue with parens and arrow functions

### LINKED ISSUE #1962: Regression concerning arrow functions
In Traceur 0.89, the following code

        this._observer = {
            onDChanged: (uuid, d) => {
                if (this.downStreamObserver)
                    this.downStreamObserver.onDChanged(uuid, d);
                this.onChanged();
            },

was compiled to this working code

      this._observer = {
        onDChanged: ($__5 = this, function(uuid, d) {
          if ($__5.downStreamObserver)
            $__5.downStreamObserver.onDChanged(uuid, d);
          $__5.onChanged();
        }),

However, starting from 0.90, some extra parentheses are gone...

    this._observer = {
        onDChanged: $__5 = this, function(uuid, d) {
          if ($__5.downStreamObserver)
            $__5.downStreamObserver.onDChanged(uuid, d);
          $__5.onChanged();
        },

which completely breaks the code, as onDChanged is basically set to "this" instead of the function intended.

### PR DESCRIPTION
**Pull request by arv**
The ParenTrait did not add the required paren around comma expressions
in object literals.

Fixes #1962

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton PTAL

File: src/codegeneration/ParenTrait.js [hunk 1]
```diff
@@ -129,5 +130,16 @@ export function ParenTrait(ParseTreeTransformerClass) {
       }
       return new ArrayLiteralExpression(tree.location, elements);
     }
+
+    transformPropertyNameAssignment(tree) {
+      let name = this.transformAny(tree.name);
+      let value = this.transformAny(tree.value);
+      if (value.type === COMMA_EXPRESSION) {
```
Comment (johnjbarton) [inline src/codegeneration/ParenTrait.js]: Is it correct that our COMMA_EXPRESSION is the grammar's AssignmentExpression?

**Comment by johnjbarton** [comment]
LGTM

File: src/codegeneration/ParenTrait.js (hunk 1 above)
Comment (arv) [inline src/codegeneration/ParenTrait.js]: No. COMMA_EXPRESSION is NOT an AssignmentExpression.

We could maybe change our code to something like `tree.isAssignmentExpression()`

Comment (johnjbarton) [inline src/codegeneration/ParenTrait.js]: So how does this work? The test case has `AssignmentExpression : ArrowFunction` and the code tests COMMA_EXPRESSION.

Comment (arv) [inline src/codegeneration/ParenTrait.js]: The arrow function gets transformed into a comma expression. This trait fixes that  so that individual transformers do not have to know about where the arrow is located in the tree.
