### PR TITLE
Always wrap the body of a for-on-loop in a block.

### LINKED ISSUE #1827: Error compiling for-on loop with 'break' body
Traceur 0.0.87 crashes while compiling the code
```Javascript
async function* x() {}

async function y() {
	for ( let a on x() )
		break
}

y()
```
The output is
```
TypeError: Value cannot be converted to an Object
    at Object.checkObjectCoercible (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:299:15)
    at Object.spread (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:1311:43)
    at InnerForOnTransformer.transform (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:19520:64)
    at Function.transform (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:19634:68)
    at ForOnTransformer.transformForOnStatement_ (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:19658:36)
    at ForOnTransformer.transformForOnStatement (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:19655:19)
    at ForOnStatement.transform (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:7374:26)
    at ForOnTransformer.transformAny (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:14104:27)
    at ForOnTransformer.transformList (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:14111:32)
    at ForOnTransformer.transformStatements_ (/home/vadzim/v/work/nerojs/node_modules/traceur/bin/traceur.js:15331:40)
```

### PR DESCRIPTION
**Pull request by mnieper**
Fixes #1827.

### CODE REVIEW

File: src/codegeneration/InnerForOnTransformer.js [hunk 1]
```diff
@@ -78,8 +78,7 @@ export class InnerForOnTransformer extends ParseTreeTransformer {
           ${tree.initializer} = ${value};`;
     }
 
-    let body = new Block(tree.body.location,
-        [assignment, ...tree.body.statements]);
+    let body = new Block(null, [assignment, tree.body]);
```
Comment (arv) [inline src/codegeneration/InnerForOnTransformer.js]: Doesn't this leads to an extra `{}` if the body is already a block?

Comment (mnieper) [inline src/codegeneration/InnerForOnTransformer.js]: Yes. In case this is unattractive, I have amended the PR.

**Comment by arv** [comment]
Thanks. LGTM
