### PR TITLE
Fixes issue for inline ES6 `export *` imports

### LINKED ISSUE #1842: outputLanguage=es6 with --inline still contains import statements
This is the source

a.js
```js
import {b} from './b.js';
export const lib = {
  b
};
```

b.js
```js
export class b {
  constructor() {}
}
```
and running ```traceur --outputLanguage=es6 --out ./out/lib.js --inline ./lib/a.js``` outputs 
```js
export class b {
  constructor() {}
}
import {b} from './b.js';
export const lib = {b};
System.get("../lib/a.js" + '');
```
or running ```traceur --modules inline --outputLanguage=es6 --out ./out/lib.js ./lib/a.js``` outputs 
```js
export class b {
  constructor() {}
}
import {b} from './b.js';
export const lib = {b};
```

```System.get("../lib/a.js" + '');``` is referencing itself? and ```imports``` shouldn't be here either

### PR DESCRIPTION
**Pull request by pflannery**
When supplying `--modules=inline --outputLanguage=es6` to the cli, any
imported `export * from ...` statements were referencing the es5
$traceurRuntime.exportStar function.

closes #1842

### CODE REVIEW

File: src/codegeneration/InlineES6ModuleTransformer.js [hunk 1]
```diff
@@ -139,6 +138,31 @@ export class InlineES6ModuleTransformer extends ModuleTransformer {
...
+    if (this.exportVisitor_.starExports.length) {
+      let starExports = this.exportVisitor_.starExports;
+      let starIdents = starExports.map((moduleSpecifier) => {
+        return createIdentifierExpression(
+          this.getTempVarNameForModuleSpecifier(moduleSpecifier));
+      });
+      statements.push(parseStatement `function exportStar(s, d) { for (let k in s) d[k] = s[k]; }`);
+      statements.push(parseStatement `let starModule = {}`);
+      statements.push(parseStatement `exportStar(${exportObject}, starModule)`);
+      starIdents.map((ident) => {
```
Comment (arv) [inline src/codegeneration/InlineES6ModuleTransformer.js]: map -> forEach since you are ignoring the return value

File: src/codegeneration/InlineES6ModuleTransformer.js [hunk 2]
```diff
@@ -139,6 +138,31 @@ export class InlineES6ModuleTransformer extends ModuleTransformer {
...
+   */
+  appendExportStatement(statements) {
+    let exportObject = createObjectLiteral(this.getExportProperties());
+    if (this.exportVisitor_.starExports.length) {
+      let starExports = this.exportVisitor_.starExports;
+      let starIdents = starExports.map((moduleSpecifier) => {
+        return createIdentifierExpression(
+          this.getTempVarNameForModuleSpecifier(moduleSpecifier));
+      });
+      statements.push(parseStatement `function exportStar(s, d) { for (let k in s) d[k] = s[k]; }`);
```
Comment (arv) [inline src/codegeneration/InlineES6ModuleTransformer.js]: Why is this function needed? Can it be inlined? Then there is less risk of naming collisions.

File: src/codegeneration/InlineES6ModuleTransformer.js [hunk 3]
```diff
@@ -139,6 +138,31 @@ export class InlineES6ModuleTransformer extends ModuleTransformer {
...
+      statements.push(parseStatement `let starModule = {}`);
```
Comment (arv) [inline src/codegeneration/InlineES6ModuleTransformer.js]: Kind of same issue here... we should at least do a gensym?

File: test/unit/codegeneration/PureES6Transformer.js [hunk 4]
```diff
@@ -70,7 +70,6 @@ suite('PureES6Transformer.js', function() {
     ].join('\n');
 
     var expected = [
-      '"use strict";',
```
Comment (arv) [inline test/unit/codegeneration/PureES6Transformer.js]: I don't understand why we should remove this? Modules should be strict.

Comment (pflannery) [inline test/unit/codegeneration/PureES6Transformer.js]: This is because the output is still es6

Comment (arv) [inline test/unit/codegeneration/PureES6Transformer.js]: I still don't get it :(

The input is a `Module` and the output is a `Script` so we need to add `"use strict"` or we get the wrong semantics.

File: src/codegeneration/InlineES6ModuleTransformer.js (hunk 3 above)
Comment (pflannery) [inline src/codegeneration/InlineES6ModuleTransformer.js]: ok. I wasn't sure how to gensym this part. Can you provide an example. thanks

Comment (arv) [inline src/codegeneration/InlineES6ModuleTransformer.js]: `ModuleTransformer` extends `TempVarTransformer` so you can use `getTempIdentifier()`.

But it is not clear why we need to generate a function here? Can't it be inlined?

Also, do we want to use for-in+[[Get]]+[[Put]] over getOwnPropertyNames + getOwnProperty + defineProperty? It is not clear to me.

**Comment by pflannery** [comment]
@arv i've generated the loop inline using gensym as requested. PTAL

**Comment by arv** [comment]
@johnjbarton Can you take a look? I'm out for two weeks.

**Comment by johnjbarton** [comment]
Yes, I will look on Sunday.

**Comment by johnjbarton** [comment]
Can we add a test case that fails before and succeeds after this fix?  The code itself looks good.

**Comment by pflannery** [comment]
@johnjbarton I finally figured out how to test `export *` statements using code generation. PTAL at the new unit test I've added.

**Comment by pflannery** [comment]
@johnjbarton I've got the test to pass without having to convert the expected code output in to a tree and back again. I've also wrapped the long line when creating the InlineES6ModuleTransformer. PTAL

**Comment by johnjbarton** [comment]
LGTM I'll merge it, Thanks!

**Comment by arv** [comment]
I merged this.

@pflannery Sorry about forgetting this.
