### PR TITLE
Fix issue with for loop initializers and block binding

### LINKED ISSUE #1637: Let bind
We incorrectly rename the inner bindings in for loops.

```js
for (let i = 0; i< 10; i++) {
  for (let i = 0; i < 10; i++) {
    for (let i = 0; i < 10; i++) {
      console.log(i)
    }
  } 
}
```

I assume the issue is that we do not treat the for initializer as being inside a block.

### PR DESCRIPTION
**Pull request by arv**
We did not correctly take the initializers in the for loop
into account. We need to stop the alpha renaming if the name
we are renaming is in a initializer that is a lexical declaration.

Fixes #1637

### CODE REVIEW

**Comment by arv** [comment]
@johnjbarton PTAL

File: src/codegeneration/ScopeTransformer.js [hunk 1]
```diff
@@ -46,9 +77,42 @@ export class ScopeTransformer extends ParseTreeTransformer {
...
+   * @param {ForInStatement} tree
+   * @return {ParseTree}
+   */
+  transformForInStatement(tree) {
+    return this.sameTreeIfNameInLoopInitializer_(tree) ||
+        super.transformForInStatement(tree);
+  }
+
+  /**
+   * @param {ForInStatement} tree
```
Comment (johnjbarton) [inline src/codegeneration/ScopeTransformer.js]: ForOfStatement

File: src/codegeneration/ScopeTransformer.js [hunk 2]
```diff
@@ -46,9 +77,42 @@ export class ScopeTransformer extends ParseTreeTransformer {
...
+  }
+
+  /**
+   * @param {ForStatement} tree
+   * @return {ParseTree}
+   */
+  transformForStatement(tree) {
+    return this.sameTreeIfNameInLoopInitializer_(tree) ||
+        super.transformForStatement(tree);
+  }
```
Comment (johnjbarton) [inline src/codegeneration/ScopeTransformer.js]: Another form could be
```js
  return this.varNameInInitializer_(tree) ? tree : super.transformForStatement(tree);
```

File: test/feature/Scope/NestedForLoops.js [hunk 3]
```diff
@@ -0,0 +1,40 @@
+// Options: --block-binding --for-of
+
+(function() {
+  var count = 0;
+  for (let x = 0; x < 1; x++) {
```
Comment (johnjbarton) [inline test/feature/Scope/NestedForLoops.js]: Do we need to test a case where the initializer includes renamable vars?
```js
for (let x=0, y=0; x * y < 1; x++, y++) {
  // inner loops over x
}
```

**Comment by johnjbarton** [comment]
LGTM

File: test/feature/Scope/NestedForLoops.js (hunk 3 above)
Comment (arv) [inline test/feature/Scope/NestedForLoops.js]: I'm not sure I understand. How is that different from these tests?
